-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, TOTAL_SUM * PRICE AS TOTAL_SALES 
FROM ( SELECT O.PRODUCT_ID, PRODUCT_NAME, PRICE, SUM(AMOUNT) AS TOTAL_SUM
        FROM FOOD_PRODUCT P JOIN FOOD_ORDER O USING (PRODUCT_ID)
        WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
        GROUP BY O.PRODUCT_ID
     ) AS TEMP
ORDER BY TOTAL_SALES desc, PRODUCT_ID asc;

# SELECT * FROM FOOD_ORDER;

# SELECT O.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT) AS TOTAL_SUM
#         FROM FOOD_PRODUCT P JOIN FOOD_ORDER O USING (PRODUCT_ID)
#         WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
#         GROUP BY O.PRODUCT_ID;