select p.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE *  AMOUNT) 'TOTAL_SALES'
from FOOD_ORDER o join FOOD_PRODUCT p
using (PRODUCT_ID)
where YEAR(PRODUCE_DATE) = 2022 and MONTH(PRODUCE_DATE) = 5
group by PRODUCT_ID
order by TOTAL_SALES desc, p.PRODUCT_ID asc;