-- 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하기
-- 할인율 적용 기간: 7일 이상 30일 미만 / 30일 이상 90일 미만 / 90일 이상
-- HISTORY에서 대여기간을 구하고 -> CAR에서 CAR_TYPE, DAILY_FEE -> PLAN에서 CAR_TYPE과 DURATION_TYPE에 해당하는 DISCOUNT_RATE 확인
-- DAILY_FEE와 DISCOUNT_RATE 곱한 후 대여기간 곱하기 -> FEE

SELECT HISTORY_ID,
    DAILY_FEE * (100-NVL(DISCOUNT_RATE, 0)) * (END_DATE - START_DATE + 1) * 0.01 AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
and P.DURATION_TYPE = (CASE WHEN END_DATE-START_DATE+1 >=90 THEN '90일 이상'
                            WHEN END_DATE-START_DATE+1 >=30 THEN '30일 이상'
                            WHEN END_DATE-START_DATE+1 >=7 THEN '7일 이상'
                      END)
WHERE C.CAR_TYPE='트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;