-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") as REVIEW_DATE
from MEMBER_PROFILE P join REST_REVIEW R 
using (MEMBER_ID)
where P.member_id = (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    )
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;