-- 2022-08 ~ 2022-10


-- 해당 기간동안 대여횟수 총 5회 이상인 차 
-- SELECT CAR_ID
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE TO_CHAR(START_DATE, 'YYYY-MM') >= '2022-08' AND TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-10'
-- GROUP BY CAR_ID
-- HAVING COUNT(*) >= 5

select EXTRACT(MONTH from START_DATE) as MONTH, CAR_ID, count(*) as RECORDS
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
where TO_CHAR(START_DATE, 'YYYY-MM') >= '2022-08' AND TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-10' and car_id in (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE, 'YYYY-MM') >= '2022-08' AND TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5)
group by EXTRACT(MONTH from START_DATE), CAR_ID
having count(*) > 0
order by month, car_id desc;